import {
  TrendingUp,
  Palette,
  Code,
  Megaphone,
  Layers,
  Sparkles,
  Target,
  Zap,
  Globe,
  Rocket,
  PenTool,
  Camera,
  ShoppingCart,
  Search,
  BarChart3,
  Users,
  Monitor,
  Smartphone,
  Mail,
  Video,
  Image as ImageIcon,
  FileText,
  Settings,
  Lightbulb,
  Award,
  Star,
  Heart,
  ThumbsUp,
  MessageSquare,
  Share2,
} from 'lucide-react';
import { LucideIcon } from 'lucide-react';

// Icon mapping - add more icons as needed
export const serviceIconMap: Record<string, LucideIcon> = {
  TrendingUp,
  Palette,
  Code,
  Megaphone,
  Layers,
  Sparkles,
  Target,
  Zap,
  Globe,
  Rocket,
  PenTool,
  Camera,
  ShoppingCart,
  Search,
  BarChart3,
  Users,
  Monitor,
  Smartphone,
  Mail,
  Video,
  ImageIcon,
  FileText,
  Settings,
  Lightbulb,
  Award,
  Star,
  Heart,
  ThumbsUp,
  MessageSquare,
  Share2,
};

// List of available icon names for Sanity dropdown
export const availableIcons = [
  { title: 'Trending Up', value: 'TrendingUp' },
  { title: 'Palette', value: 'Palette' },
  { title: 'Code', value: 'Code' },
  { title: 'Megaphone', value: 'Megaphone' },
  { title: 'Layers', value: 'Layers' },
  { title: 'Sparkles', value: 'Sparkles' },
  { title: 'Target', value: 'Target' },
  { title: 'Zap', value: 'Zap' },
  { title: 'Globe', value: 'Globe' },
  { title: 'Rocket', value: 'Rocket' },
  { title: 'Pen Tool', value: 'PenTool' },
  { title: 'Camera', value: 'Camera' },
  { title: 'Shopping Cart', value: 'ShoppingCart' },
  { title: 'Search', value: 'Search' },
  { title: 'Bar Chart', value: 'BarChart3' },
  { title: 'Users', value: 'Users' },
  { title: 'Monitor', value: 'Monitor' },
  { title: 'Smartphone', value: 'Smartphone' },
  { title: 'Mail', value: 'Mail' },
  { title: 'Video', value: 'Video' },
  { title: 'Image', value: 'ImageIcon' },
  { title: 'File Text', value: 'FileText' },
  { title: 'Settings', value: 'Settings' },
  { title: 'Lightbulb', value: 'Lightbulb' },
  { title: 'Award', value: 'Award' },
  { title: 'Star', value: 'Star' },
  { title: 'Heart', value: 'Heart' },
  { title: 'Thumbs Up', value: 'ThumbsUp' },
  { title: 'Message Square', value: 'MessageSquare' },
  { title: 'Share', value: 'Share2' },
];

// Helper function to get icon component
export function getServiceIcon(iconName?: string): LucideIcon | null {
  if (!iconName) return null;
  return serviceIconMap[iconName] || null;
}

