// Comprehensive list of country codes with proper formatting
export interface CountryCode {
  code: string;
  country: string;
  dialCode: string;
}

export const countryCodes: CountryCode[] = [
  { code: "NG", country: "Nigeria", dialCode: "+234" },
  { code: "US", country: "United States", dialCode: "+1" },
  { code: "GB", country: "United Kingdom", dialCode: "+44" },
  { code: "CA", country: "Canada", dialCode: "+1" },
  { code: "AU", country: "Australia", dialCode: "+61" },
  { code: "DE", country: "Germany", dialCode: "+49" },
  { code: "FR", country: "France", dialCode: "+33" },
  { code: "IT", country: "Italy", dialCode: "+39" },
  { code: "ES", country: "Spain", dialCode: "+34" },
  { code: "NL", country: "Netherlands", dialCode: "+31" },
  { code: "BE", country: "Belgium", dialCode: "+32" },
  { code: "CH", country: "Switzerland", dialCode: "+41" },
  { code: "AT", country: "Austria", dialCode: "+43" },
  { code: "SE", country: "Sweden", dialCode: "+46" },
  { code: "NO", country: "Norway", dialCode: "+47" },
  { code: "DK", country: "Denmark", dialCode: "+45" },
  { code: "FI", country: "Finland", dialCode: "+358" },
  { code: "PL", country: "Poland", dialCode: "+48" },
  { code: "PT", country: "Portugal", dialCode: "+351" },
  { code: "GR", country: "Greece", dialCode: "+30" },
  { code: "IE", country: "Ireland", dialCode: "+353" },
  { code: "IN", country: "India", dialCode: "+91" },
  { code: "CN", country: "China", dialCode: "+86" },
  { code: "JP", country: "Japan", dialCode: "+81" },
  { code: "KR", country: "South Korea", dialCode: "+82" },
  { code: "SG", country: "Singapore", dialCode: "+65" },
  { code: "MY", country: "Malaysia", dialCode: "+60" },
  { code: "TH", country: "Thailand", dialCode: "+66" },
  { code: "ID", country: "Indonesia", dialCode: "+62" },
  { code: "PH", country: "Philippines", dialCode: "+63" },
  { code: "VN", country: "Vietnam", dialCode: "+84" },
  { code: "BR", country: "Brazil", dialCode: "+55" },
  { code: "MX", country: "Mexico", dialCode: "+52" },
  { code: "AR", country: "Argentina", dialCode: "+54" },
  { code: "CL", country: "Chile", dialCode: "+56" },
  { code: "CO", country: "Colombia", dialCode: "+57" },
  { code: "PE", country: "Peru", dialCode: "+51" },
  { code: "ZA", country: "South Africa", dialCode: "+27" },
  { code: "EG", country: "Egypt", dialCode: "+20" },
  { code: "KE", country: "Kenya", dialCode: "+254" },
  { code: "GH", country: "Ghana", dialCode: "+233" },
  { code: "UG", country: "Uganda", dialCode: "+256" },
  { code: "TZ", country: "Tanzania", dialCode: "+255" },
  { code: "ET", country: "Ethiopia", dialCode: "+251" },
  { code: "AE", country: "United Arab Emirates", dialCode: "+971" },
  { code: "SA", country: "Saudi Arabia", dialCode: "+966" },
  { code: "IL", country: "Israel", dialCode: "+972" },
  { code: "TR", country: "Turkey", dialCode: "+90" },
  { code: "RU", country: "Russia", dialCode: "+7" },
  { code: "NZ", country: "New Zealand", dialCode: "+64" },
];

