import type { Metadata } from "next";
import Link from "next/link";
import LegalPage from "@/app/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms covering dximarketing.com, our messaging channels, event registrations and Academy applications.",
};

/**
 * DRAFT — see the note in the privacy policy. Accurate about the product;
 * not reviewed by a lawyer.
 */
export default function TermsOfService() {
  return (
    <LegalPage title="Terms of Service" updated="3 September 2026">
      <p>
        These terms cover <strong>dximarketing.com</strong>, the chat window on it, and the
        WhatsApp, Facebook Messenger and Instagram accounts DXI Marketing answers on. Using any
        of them means you accept these terms.
      </p>

      <h2>What we provide here</h2>
      <p>
        Information about DXI Marketing&apos;s services, a way to register for our events, a way
        to apply to the DXI Academy, and an assistant that answers questions and connects you to
        a person. Engagements themselves are governed by the separate agreement we sign with
        you, not by this page.
      </p>

      <h2>You are talking to software first</h2>
      <p>
        Our first reply on any channel is usually generated by an AI assistant. It will tell you
        so if you ask. It can be wrong, and it can be out of date.
      </p>
      <p>
        <strong>Nothing it says is an offer, a quote, or a commitment.</strong> Prices,
        availability, timelines and results are confirmed by a person in writing, and only that
        confirmation binds us. Ask for a person at any point and we will bring one in.
      </p>
      <p>
        We never send bank details in chat. Payment details are emailed only after an
        application is approved. If a message on any channel asks you to pay an account it sent
        you in chat, it is not from us — stop, and call us on 0807 453 3441.
      </p>

      <h2>Using these channels properly</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Send unlawful, abusive, threatening or deliberately misleading content.</li>
        <li>Send anyone else&apos;s personal data without their permission.</li>
        <li>
          Automate, flood or scrape the assistant. We rate-limit conversations and may stop
          answering one that is being abused.
        </li>
        <li>Impersonate somebody, or misrepresent who you are or who you act for.</li>
      </ul>
      <p>
        We can stop answering any conversation, and block any account, that breaks these terms.
      </p>

      <h2>Events</h2>
      <p>
        Registration is confirmed by the email we send you, and places are limited. Where an
        event has a fee, your place is confirmed once payment clears. We may change the date,
        venue or format of an event, and will tell registered attendees when we do. Refunds are
        handled case by case — write to us.
      </p>

      <h2>Academy applications</h2>
      <p>
        Applying is not being accepted. Applications are reviewed, and we may decline one
        without giving a reason. Fees, terms and what is included are set out in the offer we
        send if you are accepted.
      </p>

      <h2>Our content</h2>
      <p>
        The text, design, images and materials on this site belong to DXI Marketing. Read them,
        share a link to them, quote them with attribution. Do not republish them as your own or
        resell them.
      </p>

      <h2>Where we stand behind things, and where we do not</h2>
      <p>
        This site and these channels are provided as they are. We do not guarantee that the
        assistant is always available, always correct, or always fast, and we do not guarantee
        any particular business result from anything you read here. To the extent the law
        allows, we are not liable for indirect or consequential loss arising from your use of
        this site or these channels.
      </p>
      <p>Nothing here limits liability that cannot lawfully be limited.</p>

      <h2>Privacy</h2>
      <p>
        What we collect and why is in the <Link href="/privacy">Privacy Policy</Link>. Deleting
        it is covered on the <Link href="/data-deletion">data deletion page</Link>.
      </p>

      <h2>Changes and governing law</h2>
      <p>
        We update these terms as the service changes, and the date at the top moves with them.
        They are governed by the laws of the Federal Republic of Nigeria, and the courts of
        Lagos State have jurisdiction.
      </p>

      <h2>Contact</h2>
      <p>
        DXI Marketing, Lagos, Nigeria.
        <br />
        <a href="mailto:privacy@dximarketing.com">privacy@dximarketing.com</a> · 0807 453 3441
      </p>
    </LegalPage>
  );
}
