import type { Survey } from "@/lib/surveys";

/**
 * CFG Africa's executive questionnaire ahead of the Brand & Communications
 * 2030 session. The wording matches the printed PDF the client approved, so
 * change a prompt here only if the paper version changes with it.
 */
export const cfgBrand2030: Survey = {
  slug: "cfg-brand-2030",
  client: "CFG Africa",
  name: "Brand & Communications 2030",
  eyebrow: "CFG Africa · Executive pre-session questionnaire",
  title: "Brand & Communications",
  titleAccent: "2030",
  headline: "Where is the CFG brand today, and where should it be by 2030?",
  intro: "This questionnaire gathers each executive's view before we meet.",
  minutes: 20,
  footer: "Private & Confidential | CFG Africa",
  open: true,
  areas: [
    ["exec", "Managing Director / Executive Director"],
    ["invest", "Investment management"],
    ["advisory", "Advisory"],
    ["finance", "Finance, risk or compliance"],
    ["ops", "Operations and client services"],
    ["digital", "Digital and technology"],
    ["other", "Other"],
  ],
  sections: [
    {
      key: "today",
      title: "The brand today",
      minutes: 5,
      lede: "Where CFG stands now, in your own view. First instincts are more useful than polished answers.",
      questions: [
        {
          id: "q1",
          n: 1,
          type: "words3",
          prompt: "Which three words best describe CFG today?",
          help: "How the brand actually comes across, not how we would like it to.",
        },
        {
          id: "q2",
          n: 2,
          type: "single",
          prompt: "Which of these is CFG best known for today?",
          help: "Pick the one that comes to mind first.",
          other: true,
          columns: 2,
          options: [
            ["performance", "Investment performance and returns"],
            ["advisory", "Corporate advisory and deal work"],
            ["service", "Personal service and relationships"],
            ["integrity", "Integrity and governance"],
            ["innovation", "Innovation and digital products"],
            ["nothing", "Not yet well known for anything specific"],
            ["other", "Something else"],
          ],
        },
        {
          id: "q3",
          n: 3,
          type: "rating",
          prompt: "Rate the CFG brand today on each of these.",
          lo: "Very weak",
          hi: "Very strong",
          items: [
            ["trust", "Trust and credibility"],
            ["visibility", "Visibility in the market"],
            ["clarity", "Clarity about what we do"],
            ["young", "Relevance to young investors"],
            ["digital", "Strength of our digital presence"],
            ["consistency", "Consistency across everything we put out"],
          ],
        },
        {
          id: "q4",
          n: 4,
          type: "single",
          prompt: "In the last 12 months, where did most new clients first hear about CFG?",
          help: "Pick the single biggest source. If you don't know, say so; that is useful too.",
          other: true,
          columns: 2,
          options: [
            ["referral", "Referral from an existing client"],
            ["rm", "Relationship managers and business development"],
            ["network", "Executives' personal networks"],
            ["events", "Events and conferences"],
            ["online", "Online search or social media"],
            ["media", "Media coverage"],
            ["partners", "Partners and intermediaries"],
            ["unsure", "I don't know"],
            ["other", "Something else"],
          ],
        },
        {
          id: "q5",
          n: 5,
          type: "fields",
          prompt: "Which competitor's brand do you most admire, locally and internationally?",
          help: "The international brand is optional.",
          fields: [
            ["local", "Local brand you admire most", "short"],
            ["localwhy", "What do they do that we don't?", "long"],
            ["intl", "International brand you admire most (optional)", "short"],
            ["intlwhy", "What do they do that we don't? (optional)", "long"],
          ],
        },
        {
          id: "q6",
          n: 6,
          type: "text",
          prompt: "If we could fix only one brand problem in 2027, what would it be?",
        },
      ],
    },
    {
      key: "perception",
      title: "How others see us",
      minutes: 3,
      lede: "The gap between how we see ourselves and how others see us is usually where the brand work starts.",
      questions: [
        {
          id: "q7",
          n: 7,
          type: "matrix",
          prompt: "How do you think each group sees CFG today?",
          rows: [
            ["inst", "Institutional clients and corporates"],
            ["hnwi", "High-net-worth individuals"],
            ["retail", "Young professionals and retail investors"],
            ["reg", "Regulators (SEC and others)"],
            ["staff", "Our own staff"],
            ["media", "Financial media"],
          ],
          cols: [
            ["unaware", "Doesn't know us"],
            ["neutral", "Knows us, no strong view"],
            ["positive", "Positive"],
            ["advocate", "Strong advocate"],
            ["mixed", "Mixed or negative"],
            ["unsure", "Not sure"],
          ],
        },
        {
          id: "q8",
          n: 8,
          type: "text",
          prompt:
            "Where is the biggest gap between how we see ourselves and how the market sees us?",
        },
        {
          id: "q9",
          n: 9,
          type: "text",
          prompt: "What is one thing people get wrong about CFG?",
        },
      ],
    },
    {
      key: "vision",
      title: "The 2030 vision",
      minutes: 4,
      lede: "CFG's 2030 vision is not yet written down. These questions capture what each executive believes it should be, and what it will take to get there.",
      questions: [
        {
          id: "q10",
          n: 10,
          type: "text",
          prompt: "In your own words, what should CFG aim to be by 2030?",
          help: "Two or three sentences. Think about size, reach, reputation and the clients we serve.",
        },
        {
          id: "q11",
          n: 11,
          type: "three",
          fieldLabel: "Must-have",
          prompt: "Name three things CFG must have in place to achieve the 2030 vision.",
          help: "Anything at all: people, capital, licences, products, technology, brand, partnerships.",
        },
        {
          id: "q12",
          n: 12,
          type: "single",
          prompt: "What role should the brand play in reaching that vision?",
          comment: "Why? (one line)",
          options: [
            ["protect", "Protect", "Keep us credible and compliant. Growth comes from elsewhere."],
            [
              "support",
              "Support",
              "Make it easier for relationship managers and partners to win business.",
            ],
            ["drive", "Drive", "Bring clients to us on its own, through visibility and reputation."],
            [
              "differentiate",
              "Differentiate",
              "Be the main reason clients choose CFG over competitors.",
            ],
          ],
        },
        {
          id: "q13",
          n: 13,
          type: "single",
          prompt: "What role should technology play in reaching that vision?",
          comment: "Why? (one line)",
          options: [
            ["efficiency", "Efficiency", "Run operations faster and cheaper behind the scenes."],
            ["experience", "Client experience", "Make CFG easier to deal with for existing clients."],
            [
              "distribution",
              "Distribution",
              "Reach new clients we can't reach today, through apps, partners and digital onboarding.",
            ],
            ["core", "Core product", "Technology is the product we sell."],
          ],
        },
      ],
    },
    {
      key: "ambition",
      title: "Ambition for 2030",
      minutes: 4,
      lede: "Where the brand should be by 2030. Be as ambitious as you believe is realistic.",
      questions: [
        {
          id: "q14",
          n: 14,
          type: "words3",
          prompt: "Which three words should describe CFG in 2030?",
        },
        {
          id: "q15",
          n: 15,
          type: "rank",
          prompt: "Rank these audiences by importance to CFG's growth between now and 2030.",
          help: "Tap them in order of importance, most important first.",
          items: [
            ["inst", "Institutions and corporates"],
            ["hnwi", "High-net-worth individuals"],
            ["retail", "Young professionals and retail investors"],
            ["diaspora", "Nigerians in the diaspora"],
            ["partners", "Partner platforms (fintechs, employers, marketplaces)"],
          ],
        },
        {
          id: "q16",
          n: 16,
          type: "multi",
          prompt: "Where should CFG be a recognised name by 2030?",
          help: "Tick all that apply.",
          columns: 2,
          options: [
            ["nigeria", "Across Nigeria"],
            ["westafrica", "West Africa"],
            ["africa", "Pan-African"],
            ["europe", "Europe"],
            ["usa", "USA"],
          ],
        },
        {
          id: "q17",
          n: 17,
          type: "rank",
          prompt:
            "Rank these client needs by how strongly CFG should be known for meeting them by 2030.",
          help: "Tap them in order of importance, most important first.",
          items: [
            ["grow", "Growing wealth"],
            ["protect", "Protecting wealth and assets"],
            ["capital", "Raising capital and growing businesses"],
            ["legacy", "Planning for retirement and the next generation"],
            ["simple", "Making saving and investing simple"],
          ],
        },
      ],
    },
    {
      key: "positioning",
      title: "Brand personality: today and 2030",
      minutes: 4,
      lede: "Each question below is a scale between two opposite ways a financial brand can come across. Neither end is better; strong brands choose their position on purpose. On the first scale, mark where CFG sits today; on the second, where it should sit by 2030. 0 is fully at the left end, 10 is fully at the right, and 5 is an even balance. The distance between the two answers shows how far you think the brand needs to move.",
      questions: [
        {
          id: "q18",
          n: 18,
          type: "slider",
          prompt: "Institutional or accessible?",
          help: "Does CFG feel built for large institutions, or open and easy for individual investors to approach?",
          lo: "Institutional",
          hi: "Accessible",
        },
        {
          id: "q19",
          n: 19,
          type: "slider",
          prompt: "Conservative or bold?",
          help: "Does CFG's voice play it safe, or take clear positions and try new things?",
          lo: "Conservative",
          hi: "Bold",
        },
        {
          id: "q20",
          n: 20,
          type: "slider",
          prompt: "Product-led or advice-led?",
          help: "Do we lead with funds and returns, or with guidance and the relationship?",
          lo: "Product-led",
          hi: "Advice-led",
        },
        {
          id: "q21",
          n: 21,
          type: "slider",
          prompt: "Quiet performer or visible thought leader?",
          help: "Do we let results speak for themselves, or show up publicly with views on markets and the economy?",
          lo: "Quiet performer",
          hi: "Visible thought leader",
        },
        {
          id: "q22",
          n: 22,
          type: "slider",
          prompt: "Exclusive or inclusive?",
          help: "Is CFG for a select group of clients, or for a broad range of Nigerians?",
          lo: "Premium and exclusive",
          hi: "Broad and inclusive",
        },
      ],
    },
    {
      key: "comms",
      title: "Communication",
      minutes: 2,
      lede: "How and where CFG should show up.",
      questions: [
        {
          id: "q23",
          n: 23,
          type: "multi",
          max: 3,
          prompt: "Which three channels matter most for CFG over the next two years?",
          columns: 2,
          options: [
            ["social", "Social media (LinkedIn, Instagram, TikTok, X)"],
            ["youtube", "YouTube and video"],
            ["google", "Google search and online advertising"],
            ["pr", "Media and PR"],
            ["events", "Events and roundtables"],
            ["whatsapp", "WhatsApp communities"],
            ["rms", "Relationship managers"],
            ["partners", "Partner platforms"],
            ["web", "Website, research and newsletters"],
            ["apps", "Our digital products and mobile apps"],
          ],
        },
        {
          id: "q24",
          n: 24,
          type: "single",
          prompt: "Who should be the public face of CFG?",
          options: [
            ["md", "The Managing Director"],
            ["invest", "The investment team"],
            ["spokes", "A dedicated spokesperson"],
            ["brand", "The brand itself, with no single face"],
            ["mix", "A mix, depending on the audience"],
          ],
        },
      ],
    },
  ],
};
